local monitors = require("modules.monitors")
local general = require("modules.general")
local animations = require("modules.animations")
local misc = require("modules.misc")
local input = require("modules.input")
local keybinds = require("modules.keybinds")
local windowrules = require("modules.windowrules")
local minecraft = require("modules.minecraft")

monitors.setup(hl)
general.setup(hl)
animations.setup(hl)
misc.setup(hl)
input.setup(hl)
keybinds.setup(hl)
windowrules.setup(hl)
minecraft.setup(hl)
